version: '3.1'
  
services:
  postgres:
    image: postgres:latest
    container_name: pattern_d_db
    restart: always
      
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: patternd

networks:
  default:
    external: true
    name: pattern_d_network